// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wbmc.info.proto

#ifndef PROTOBUF_wbmc_2einfo_2eproto__INCLUDED
#define PROTOBUF_wbmc_2einfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace wbmc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_wbmc_2einfo_2eproto();
void protobuf_AssignDesc_wbmc_2einfo_2eproto();
void protobuf_ShutdownFile_wbmc_2einfo_2eproto();

class Info;

// ===================================================================

class Info : public ::google::protobuf::Message {
 public:
  Info();
  virtual ~Info();

  Info(const Info& from);

  inline Info& operator=(const Info& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Info& default_instance();

  void Swap(Info* other);

  // implements Message ----------------------------------------------

  Info* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Info& from);
  void MergeFrom(const Info& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 qq = 1;
  inline bool has_qq() const;
  inline void clear_qq();
  static const int kQqFieldNumber = 1;
  inline ::google::protobuf::int32 qq() const;
  inline void set_qq(::google::protobuf::int32 value);

  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional int32 years = 3;
  inline bool has_years() const;
  inline void clear_years();
  static const int kYearsFieldNumber = 3;
  inline ::google::protobuf::int32 years() const;
  inline void set_years(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:wbmc.Info)
 private:
  inline void set_has_qq();
  inline void clear_has_qq();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_years();
  inline void clear_has_years();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::google::protobuf::int32 qq_;
  ::google::protobuf::int32 years_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_wbmc_2einfo_2eproto();
  friend void protobuf_AssignDesc_wbmc_2einfo_2eproto();
  friend void protobuf_ShutdownFile_wbmc_2einfo_2eproto();

  void InitAsDefaultInstance();
  static Info* default_instance_;
};
// ===================================================================


// ===================================================================

// Info

// required int32 qq = 1;
inline bool Info::has_qq() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Info::set_has_qq() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Info::clear_has_qq() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Info::clear_qq() {
  qq_ = 0;
  clear_has_qq();
}
inline ::google::protobuf::int32 Info::qq() const {
  return qq_;
}
inline void Info::set_qq(::google::protobuf::int32 value) {
  set_has_qq();
  qq_ = value;
}

// required string name = 2;
inline bool Info::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Info::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Info::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Info::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Info::name() const {
  return *name_;
}
inline void Info::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Info::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Info::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Info::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Info::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Info::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 years = 3;
inline bool Info::has_years() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Info::set_has_years() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Info::clear_has_years() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Info::clear_years() {
  years_ = 0;
  clear_has_years();
}
inline ::google::protobuf::int32 Info::years() const {
  return years_;
}
inline void Info::set_years(::google::protobuf::int32 value) {
  set_has_years();
  years_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace wbmc

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_wbmc_2einfo_2eproto__INCLUDED
